name: /Users/anthonybiel/Documents/ReservationNuances/.conda
channels:
  - defaults
dependencies:
  - abseil-cpp=20230802.0=h313beb8_2
  - anyio=4.2.0=py311hca03da5_0
  - appnope=0.1.2=py311hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h80987f9_0
  - arrow-cpp=14.0.2=hc7aafb3_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py311hca03da5_0
  - attrs=23.1.0=py311hca03da5_0
  - aws-c-auth=0.6.19=h80987f9_0
  - aws-c-cal=0.5.20=h80987f9_0
  - aws-c-common=0.8.5=h80987f9_0
  - aws-c-compression=0.2.16=h80987f9_0
  - aws-c-event-stream=0.2.15=h313beb8_0
  - aws-c-http=0.6.25=h80987f9_0
  - aws-c-io=0.13.10=h80987f9_0
  - aws-c-mqtt=0.7.13=h80987f9_0
  - aws-c-s3=0.1.51=h80987f9_0
  - aws-c-sdkutils=0.1.6=h80987f9_0
  - aws-checksums=0.1.13=h80987f9_0
  - aws-crt-cpp=0.18.16=h313beb8_0
  - aws-sdk-cpp=1.10.55=h313beb8_0
  - babel=2.11.0=py311hca03da5_0
  - beautifulsoup4=4.12.2=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py311h313beb8_7
  - bzip2=1.0.8=h80987f9_5
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2024.3.11=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2024.2.2=py311hca03da5_0
  - cffi=1.16.0=py311h80987f9_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - comm=0.2.1=py311hca03da5_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - gflags=2.2.2=h313beb8_1
  - glog=0.5.0=h313beb8_1
  - grpc-cpp=1.48.2=hc60591f_4
  - gtest=1.14.0=h48ca7d4_0
  - icu=73.1=h313beb8_0
  - idna=3.4=py311hca03da5_0
  - ipykernel=6.28.0=py311hca03da5_0
  - ipython=8.20.0=py311hca03da5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_2
  - jedi=0.18.1=py311hca03da5_1
  - jinja2=3.1.3=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.19.2=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupyter-lsp=2.2.0=py311hca03da5_0
  - jupyter_client=8.6.0=py311hca03da5_0
  - jupyter_core=5.5.0=py311hca03da5_0
  - jupyter_events=0.8.0=py311hca03da5_0
  - jupyter_server=2.10.0=py311hca03da5_0
  - jupyter_server_terminals=0.4.4=py311hca03da5_1
  - jupyterlab=4.0.11=py311hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.25.1=py311hca03da5_0
  - jupyterlab_widgets=3.0.10=py311hca03da5_0
  - krb5=1.20.1=hf3e1bf2_1
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libboost=1.82.0=h0bc93f9_2
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcurl=8.5.0=h3e2b118_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h1a28f6b_2
  - libnghttp2=1.57.0=h62f6fdd_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libssh2=1.10.0=h02f6b3c_2
  - libthrift=0.15.0=h73c2103_2
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.3=py311h80987f9_0
  - matplotlib-inline=0.1.6=py311hca03da5_0
  - mistune=2.0.4=py311hca03da5_0
  - nbclient=0.8.0=py311hca03da5_0
  - nbconvert=7.10.0=py311hca03da5_0
  - nbformat=5.9.2=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - notebook=7.0.8=py311hca03da5_0
  - notebook-shim=0.2.3=py311hca03da5_0
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.0.13=h1a28f6b_0
  - orc=1.7.4=hdca1487_1
  - overrides=7.4.0=py311hca03da5_0
  - packaging=23.2=py311hca03da5_0
  - pandas=2.2.1=py311h7aedaa7_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=10.2.0=py311h80987f9_0
  - pip=23.3.1=py311hca03da5_0
  - platformdirs=3.10.0=py311hca03da5_0
  - prometheus_client=0.14.1=py311hca03da5_0
  - prompt-toolkit=3.0.43=py311hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=3.20.3=py311h313beb8_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hca03da5_1
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.8=hb885b13_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311hca03da5_0
  - python-json-logger=2.0.7=py311hca03da5_0
  - pytz=2023.3.post1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=25.1.2=py311h313beb8_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py311hca03da5_0
  - requests=2.31.0=py311hca03da5_1
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rpds-py=0.10.6=py311hf0e4da2_0
  - send2trash=1.8.2=py311hca03da5_0
  - setuptools=68.2.2=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h313beb8_1
  - sniffio=1.3.0=py311hca03da5_0
  - soupsieve=2.5=py311hca03da5_0
  - sqlite=3.41.2=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py311hca03da5_0
  - tinycss2=1.2.1=py311hca03da5_0
  - tk=8.6.12=hb8d0fd4_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.3.3=py311h80987f9_0
  - traitlets=5.7.1=py311hca03da5_0
  - urllib3=2.1.0=py311hca03da5_1
  - utf8proc=2.6.1=h80987f9_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=0.58.0=py311hca03da5_4
  - wheel=0.41.2=py311hca03da5_0
  - widgetsnbextension=3.5.2=py311hca03da5_1
  - xz=5.4.6=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zlib=1.2.13=h5a0b063_0
  - zstd=1.5.5=hd90d995_0
  - pip:
      - altair==5.2.0
      - blinker==1.7.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - google-api-core==2.17.1
      - google-api-python-client==2.122.0
      - google-auth==2.28.2
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.0
      - googleapis-common-protos==1.63.0
      - httplib2==0.22.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - oauthlib==3.2.2
      - pip-autoremove==0.10.0
      - pyarrow==15.0.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydeck==0.8.1b0
      - pyjwt==2.8.0
      - pyparsing==3.1.2
      - requests-oauthlib==1.4.0
      - rich==13.7.1
      - rsa==4.9
      - smmap==5.0.1
      - streamlit==1.32.2
      - streamlit-js-eval==0.1.7
      - tenacity==8.2.3
      - toolz==0.12.1
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - uritemplate==4.1.1
prefix: /Users/anthonybiel/Documents/ReservationNuances/.conda
